### ISSUE TITLE
Add README file

### ISSUE THREAD

**Issue by sanand0** [thejeshgn/DB_USERMETA#1]
Sorry, I'm sure you meant to add a README file. Just bumped into this repo, and it seems to overlap with some stuff I've been thinking about. Thought I'd pitch in if I understood the context better...

**Comment by thejeshgn** [comment]
@sanand0 I have few of the datasets in SQLITE format. I wanted to add codebook (or metadata) about 
the database in a table called DB_USERMETA in the same DB. DB_USERMETA is a keyvalue table with predefined keys. 

I didnt get any alert for this issue and hence the delay reply. I will add a readme.

**Comment by sanand0** [comment]
Thanks! I understand this better now. I thought you were looking to _automatically_ generate metadata about a database, which is something I'm working on, but I see this is in a different (probably more useful!) direction.

**Comment by thejeshgn** [comment]
it could be a mix.

## Thej

Thejesh GN _⏚_ ತೇಜೇಶ್ ಜಿ.ಎನ್
http://thejeshgn.com
GPG ID :  0xBFFC8DD3C06DD6B0
